import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:slservers/data/servers.dart';
import 'package:slservers/models/server.dart';
import 'package:stylight/stylight.dart';

import 'markdown_editor.dart';

class ServerDescriptionWidget extends StatefulWidget {
  ServerDescriptionWidget({Key key, this.server}) : super(key: key);

  Server server;

  @override
  _ServerDescriptionWidgetState createState() => _ServerDescriptionWidgetState(server);
}

class _ServerDescriptionWidgetState extends State<ServerDescriptionWidget> {

  Server server;


  _ServerDescriptionWidgetState(this.server);

  @override
  void initState() {
    if (server==null) server = new Server(languages: [], comments: [], instances: [], tags: [], rules: [], autogenerated: false, visible: false, description: "");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    size = new Size((size.width / 5 ) * 4, size.height);
    return ListView(
      children: [
        Container(height: 64,),
        Padding(
          padding: const EdgeInsets.all(16.0),
          child: TextStyles.Title1.text("Server Description"),
        ),

        Padding(
          padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 16),
          child: Container(
              child: MarkdownEditor(width: (size.width) - 32, callback: (s) => server.description = s, initial: server.description,)),
        ),

        Container(height: 16,),

        Center(
          child: RaisedButton(child: Text("Save"), onPressed: () async {
            print(jsonEncode(server.toJson()));
            await Servers.update(server);
            success(context, "Server settings updated");
          }),
        ),
      ],
    );
  }
}